# Generated by Django 2.0.7 on 2018-07-29 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='continent',
            new_name='country',
        ),
    ]
