# Generated by Django 2.0.7 on 2018-07-29 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180729_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hack',
            old_name='desciption',
            new_name='description',
        ),
    ]
