# Generated by Django 2.0.7 on 2018-07-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180729_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hack',
            options={},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.AddField(
            model_name='hack',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
    ]
