# Generated by Django 2.0.7 on 2018-07-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180729_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='hack',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
